/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: sgp.i

package sgp

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _goslice_ swig_type_1;
typedef _goslice_ swig_type_2;
typedef long long swig_type_3;
typedef long long swig_type_4;
typedef _gostring_ swig_type_5;
typedef _gostring_ swig_type_6;
typedef long long swig_type_7;
typedef long long swig_type_8;
typedef long long swig_type_9;
typedef long long swig_type_10;
typedef long long swig_type_11;
typedef long long swig_type_12;
extern void _wrap_Swig_free_sgp_8b5016feffcb84af(uintptr_t arg1);
extern _Bool _wrap_modifiedSGP4_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2, swig_type_1 arg3, swig_type_2 arg4);
extern swig_intgo _wrap_wgs72old_sgp_8b5016feffcb84af(void);
extern swig_intgo _wrap_wgs72_sgp_8b5016feffcb84af(void);
extern swig_intgo _wrap_wgs84_sgp_8b5016feffcb84af(void);
extern void _wrap_elsetrec_number_set_sgp_8b5016feffcb84af(uintptr_t arg1, swig_type_3 arg2);
extern swig_type_4 _wrap_elsetrec_number_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_year_set_sgp_8b5016feffcb84af(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_elsetrec_year_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_epochtynumrev_set_sgp_8b5016feffcb84af(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_elsetrec_epochtynumrev_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_error_set_sgp_8b5016feffcb84af(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_elsetrec_error_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_operationmode_set_sgp_8b5016feffcb84af(uintptr_t arg1, char arg2);
extern char _wrap_elsetrec_operationmode_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_init_set_sgp_8b5016feffcb84af(uintptr_t arg1, char arg2);
extern char _wrap_elsetrec_init_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_method_set_sgp_8b5016feffcb84af(uintptr_t arg1, char arg2);
extern char _wrap_elsetrec_method_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_isimp_set_sgp_8b5016feffcb84af(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_elsetrec_isimp_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_aycof_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_aycof_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_con41_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_con41_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_cc1_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_cc1_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_cc4_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_cc4_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_cc5_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_cc5_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_d2_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_d2_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_d3_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_d3_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_d4_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_d4_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_delmo_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_delmo_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_eta_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_eta_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_argpdot_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_argpdot_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_omgcof_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_omgcof_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_sinmao_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_sinmao_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_t_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_t_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_t2cof_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_t2cof_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_t3cof_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_t3cof_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_t4cof_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_t4cof_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_t5cof_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_t5cof_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_x1mth2_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_x1mth2_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_x7thm1_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_x7thm1_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_mdot_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_mdot_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_nodedot_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_nodedot_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_xlcof_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_xlcof_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_xmcof_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_xmcof_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_nodecf_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_nodecf_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_irez_set_sgp_8b5016feffcb84af(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_elsetrec_irez_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_d2201_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_d2201_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_d2211_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_d2211_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_d3210_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_d3210_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_d3222_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_d3222_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_d4410_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_d4410_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_d4422_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_d4422_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_d5220_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_d5220_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_d5232_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_d5232_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_d5421_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_d5421_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_d5433_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_d5433_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_dedt_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_dedt_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_del1_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_del1_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_del2_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_del2_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_del3_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_del3_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_didt_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_didt_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_dmdt_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_dmdt_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_dnodt_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_dnodt_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_domdt_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_domdt_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_e3_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_e3_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_ee2_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_ee2_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_peo_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_peo_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_pgho_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_pgho_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_pho_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_pho_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_pinco_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_pinco_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_plo_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_plo_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_se2_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_se2_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_se3_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_se3_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_sgh2_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_sgh2_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_sgh3_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_sgh3_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_sgh4_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_sgh4_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_sh2_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_sh2_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_sh3_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_sh3_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_si2_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_si2_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_si3_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_si3_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_sl2_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_sl2_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_sl3_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_sl3_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_sl4_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_sl4_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_gsto_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_gsto_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_xfact_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_xfact_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_xgh2_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_xgh2_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_xgh3_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_xgh3_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_xgh4_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_xgh4_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_xh2_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_xh2_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_xh3_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_xh3_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_xi2_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_xi2_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_xi3_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_xi3_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_xl2_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_xl2_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_xl3_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_xl3_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_xl4_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_xl4_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_xlamo_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_xlamo_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_zmol_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_zmol_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_zmos_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_zmos_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_atime_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_atime_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_xli_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_xli_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_xni_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_xni_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_a_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_a_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_altp_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_altp_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_alta_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_alta_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_days_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_days_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_jdsatepoch_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_jdsatepoch_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_jdsatepochF_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_jdsatepochF_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_mean2_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_mean2_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_mean1_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_mean1_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_bstar_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_bstar_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_rcse_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_rcse_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_inclination_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_inclination_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_ascension_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_ascension_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_excentricity_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_excentricity_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_perigee_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_perigee_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_anomaly_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_anomaly_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_motion_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_motion_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_classification_set_sgp_8b5016feffcb84af(uintptr_t arg1, char arg2);
extern char _wrap_elsetrec_classification_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_designation_set_sgp_8b5016feffcb84af(uintptr_t arg1, swig_type_5 arg2);
extern swig_type_6 _wrap_elsetrec_designation_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_ephemeris_set_sgp_8b5016feffcb84af(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_elsetrec_ephemeris_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_elnum_set_sgp_8b5016feffcb84af(uintptr_t arg1, swig_type_7 arg2);
extern swig_type_8 _wrap_elsetrec_elnum_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_revnum_set_sgp_8b5016feffcb84af(uintptr_t arg1, swig_type_9 arg2);
extern swig_type_10 _wrap_elsetrec_revnum_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_no_unkozai_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_no_unkozai_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_am_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_am_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_em_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_em_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_im_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_im_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_Om_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_Om_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_mm_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_mm_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_nm_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_nm_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_tumin_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_tumin_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_mu_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_mu_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_radiusearthkm_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_radiusearthkm_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_xke_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_xke_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_j2_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_j2_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_j3_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_j3_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_j4_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_j4_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_j3oj2_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_j3oj2_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_dia_mm_set_sgp_8b5016feffcb84af(uintptr_t arg1, swig_type_11 arg2);
extern swig_type_12 _wrap_elsetrec_dia_mm_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_period_sec_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_period_sec_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_active_set_sgp_8b5016feffcb84af(uintptr_t arg1, char arg2);
extern char _wrap_elsetrec_active_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_not_orbital_set_sgp_8b5016feffcb84af(uintptr_t arg1, char arg2);
extern char _wrap_elsetrec_not_orbital_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern void _wrap_elsetrec_rcs_m2_set_sgp_8b5016feffcb84af(uintptr_t arg1, double arg2);
extern double _wrap_elsetrec_rcs_m2_get_sgp_8b5016feffcb84af(uintptr_t arg1);
extern uintptr_t _wrap_new_elsetrec_sgp_8b5016feffcb84af(void);
extern void _wrap_delete_elsetrec_sgp_8b5016feffcb84af(uintptr_t arg1);
extern _Bool _wrap_sgp4init_sgp_8b5016feffcb84af(swig_intgo arg1, char arg2, swig_intgo arg3, double arg4, double arg5, double arg6, double arg7, double arg8, double arg9, double arg10, double arg11, double arg12, double arg13, uintptr_t arg14);
extern void _wrap_getgravconst_sgp_8b5016feffcb84af(swig_intgo arg1, swig_voidp arg2, swig_voidp arg3, swig_voidp arg4, swig_voidp arg5, swig_voidp arg6, swig_voidp arg7, swig_voidp arg8, swig_voidp arg9);
extern double _wrap_gstime_sgp_8b5016feffcb84af(double arg1);
extern double _wrap_sgn_sgp_8b5016feffcb84af(double arg1);
extern double _wrap_mag_sgp_8b5016feffcb84af(swig_voidp arg1);
extern void _wrap_cross_sgp_8b5016feffcb84af(swig_voidp arg1, swig_voidp arg2, swig_voidp arg3);
extern double _wrap_dot_sgp_8b5016feffcb84af(swig_voidp arg1, swig_voidp arg2);
extern double _wrap_angle_sgp_8b5016feffcb84af(swig_voidp arg1, swig_voidp arg2);
extern void _wrap_newtonnu_sgp_8b5016feffcb84af(double arg1, double arg2, swig_voidp arg3, swig_voidp arg4);
extern double _wrap_asinh_sgp_8b5016feffcb84af(double arg1);
extern void _wrap_rv2coe_sgp_8b5016feffcb84af(swig_voidp arg1, swig_voidp arg2, double arg3, swig_voidp arg4, swig_voidp arg5, swig_voidp arg6, swig_voidp arg7, swig_voidp arg8, swig_voidp arg9, swig_voidp arg10, swig_voidp arg11, swig_voidp arg12, swig_voidp arg13, swig_voidp arg14);
extern void _wrap_jday_sgp_8b5016feffcb84af(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4, swig_intgo arg5, double arg6, swig_voidp arg7, swig_voidp arg8);
extern void _wrap_days2mdhms_sgp_8b5016feffcb84af(swig_intgo arg1, double arg2, swig_voidp arg3, swig_voidp arg4, swig_voidp arg5, swig_voidp arg6, swig_voidp arg7);
extern void _wrap_invjday_sgp_8b5016feffcb84af(double arg1, double arg2, swig_voidp arg3, swig_voidp arg4, swig_voidp arg5, swig_voidp arg6, swig_voidp arg7, swig_voidp arg8);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"
import "fmt"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0))
}

func ModifiedSGP4(arg1 Elsetrec, arg2 float64, arg3 []float64, arg4 []float64) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (bool)(C._wrap_modifiedSGP4_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), *(*C.swig_type_1)(unsafe.Pointer(&_swig_i_2)), *(*C.swig_type_2)(unsafe.Pointer(&_swig_i_3))))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
	return swig_r
}

const SGP4Version string = "SGP4 Version 2016-03-09"
type Gravconsttype int
func _swig_getwgs72old() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_wgs72old_sgp_8b5016feffcb84af())
	return swig_r
}

var Wgs72old int = _swig_getwgs72old()
func _swig_getwgs72() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_wgs72_sgp_8b5016feffcb84af())
	return swig_r
}

var Wgs72 int = _swig_getwgs72()
func _swig_getwgs84() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_wgs84_sgp_8b5016feffcb84af())
	return swig_r
}

var Wgs84 int = _swig_getwgs84()
type SwigcptrElsetrec uintptr

func (p SwigcptrElsetrec) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrElsetrec) SwigIsElsetrec() {
}

func (arg1 SwigcptrElsetrec) SetNumber(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_number_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.swig_type_3(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetNumber() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_elsetrec_number_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetYear(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_year_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetYear() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_elsetrec_year_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetEpochtynumrev(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_epochtynumrev_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetEpochtynumrev() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_elsetrec_epochtynumrev_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetError(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_error_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetError() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_elsetrec_error_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetOperationmode(arg2 byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_operationmode_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.char(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetOperationmode() (_swig_ret byte) {
	var swig_r byte
	_swig_i_0 := arg1
	swig_r = (byte)(C._wrap_elsetrec_operationmode_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetInit(arg2 byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_init_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.char(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetInit() (_swig_ret byte) {
	var swig_r byte
	_swig_i_0 := arg1
	swig_r = (byte)(C._wrap_elsetrec_init_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetMethod(arg2 byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_method_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.char(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetMethod() (_swig_ret byte) {
	var swig_r byte
	_swig_i_0 := arg1
	swig_r = (byte)(C._wrap_elsetrec_method_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetIsimp(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_isimp_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetIsimp() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_elsetrec_isimp_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetAycof(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_aycof_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetAycof() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_aycof_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetCon41(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_con41_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetCon41() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_con41_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetCc1(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_cc1_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetCc1() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_cc1_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetCc4(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_cc4_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetCc4() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_cc4_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetCc5(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_cc5_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetCc5() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_cc5_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetD2(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_d2_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetD2() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_d2_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetD3(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_d3_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetD3() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_d3_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetD4(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_d4_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetD4() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_d4_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetDelmo(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_delmo_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetDelmo() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_delmo_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetEta(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_eta_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetEta() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_eta_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetArgpdot(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_argpdot_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetArgpdot() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_argpdot_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetOmgcof(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_omgcof_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetOmgcof() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_omgcof_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetSinmao(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_sinmao_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetSinmao() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_sinmao_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetT(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_t_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetT() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_t_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetT2cof(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_t2cof_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetT2cof() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_t2cof_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetT3cof(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_t3cof_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetT3cof() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_t3cof_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetT4cof(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_t4cof_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetT4cof() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_t4cof_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetT5cof(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_t5cof_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetT5cof() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_t5cof_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetX1mth2(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_x1mth2_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetX1mth2() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_x1mth2_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetX7thm1(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_x7thm1_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetX7thm1() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_x7thm1_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetMdot(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_mdot_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetMdot() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_mdot_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetNodedot(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_nodedot_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetNodedot() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_nodedot_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetXlcof(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_xlcof_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetXlcof() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_xlcof_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetXmcof(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_xmcof_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetXmcof() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_xmcof_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetNodecf(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_nodecf_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetNodecf() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_nodecf_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetIrez(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_irez_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetIrez() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_elsetrec_irez_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetD2201(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_d2201_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetD2201() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_d2201_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetD2211(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_d2211_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetD2211() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_d2211_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetD3210(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_d3210_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetD3210() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_d3210_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetD3222(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_d3222_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetD3222() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_d3222_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetD4410(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_d4410_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetD4410() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_d4410_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetD4422(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_d4422_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetD4422() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_d4422_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetD5220(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_d5220_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetD5220() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_d5220_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetD5232(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_d5232_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetD5232() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_d5232_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetD5421(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_d5421_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetD5421() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_d5421_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetD5433(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_d5433_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetD5433() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_d5433_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetDedt(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_dedt_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetDedt() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_dedt_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetDel1(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_del1_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetDel1() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_del1_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetDel2(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_del2_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetDel2() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_del2_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetDel3(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_del3_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetDel3() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_del3_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetDidt(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_didt_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetDidt() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_didt_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetDmdt(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_dmdt_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetDmdt() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_dmdt_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetDnodt(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_dnodt_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetDnodt() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_dnodt_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetDomdt(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_domdt_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetDomdt() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_domdt_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetE3(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_e3_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetE3() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_e3_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetEe2(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_ee2_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetEe2() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_ee2_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetPeo(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_peo_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetPeo() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_peo_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetPgho(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_pgho_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetPgho() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_pgho_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetPho(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_pho_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetPho() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_pho_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetPinco(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_pinco_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetPinco() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_pinco_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetPlo(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_plo_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetPlo() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_plo_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetSe2(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_se2_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetSe2() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_se2_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetSe3(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_se3_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetSe3() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_se3_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetSgh2(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_sgh2_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetSgh2() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_sgh2_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetSgh3(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_sgh3_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetSgh3() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_sgh3_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetSgh4(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_sgh4_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetSgh4() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_sgh4_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetSh2(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_sh2_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetSh2() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_sh2_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetSh3(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_sh3_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetSh3() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_sh3_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetSi2(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_si2_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetSi2() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_si2_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetSi3(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_si3_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetSi3() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_si3_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetSl2(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_sl2_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetSl2() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_sl2_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetSl3(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_sl3_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetSl3() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_sl3_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetSl4(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_sl4_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetSl4() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_sl4_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetGsto(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_gsto_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetGsto() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_gsto_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetXfact(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_xfact_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetXfact() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_xfact_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetXgh2(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_xgh2_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetXgh2() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_xgh2_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetXgh3(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_xgh3_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetXgh3() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_xgh3_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetXgh4(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_xgh4_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetXgh4() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_xgh4_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetXh2(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_xh2_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetXh2() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_xh2_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetXh3(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_xh3_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetXh3() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_xh3_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetXi2(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_xi2_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetXi2() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_xi2_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetXi3(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_xi3_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetXi3() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_xi3_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetXl2(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_xl2_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetXl2() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_xl2_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetXl3(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_xl3_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetXl3() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_xl3_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetXl4(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_xl4_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetXl4() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_xl4_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetXlamo(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_xlamo_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetXlamo() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_xlamo_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetZmol(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_zmol_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetZmol() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_zmol_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetZmos(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_zmos_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetZmos() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_zmos_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetAtime(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_atime_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetAtime() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_atime_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetXli(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_xli_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetXli() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_xli_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetXni(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_xni_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetXni() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_xni_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetA(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_a_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetA() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_a_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetAltp(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_altp_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetAltp() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_altp_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetAlta(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_alta_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetAlta() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_alta_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetDays(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_days_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetDays() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_days_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetJdsatepoch(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_jdsatepoch_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetJdsatepoch() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_jdsatepoch_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetJdsatepochF(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_jdsatepochF_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetJdsatepochF() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_jdsatepochF_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetMean2(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_mean2_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetMean2() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_mean2_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetMean1(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_mean1_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetMean1() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_mean1_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetBstar(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_bstar_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetBstar() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_bstar_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetRcse(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_rcse_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetRcse() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_rcse_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetInclination(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_inclination_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetInclination() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_inclination_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetAscension(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_ascension_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetAscension() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_ascension_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetExcentricity(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_excentricity_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetExcentricity() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_excentricity_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetPerigee(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_perigee_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetPerigee() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_perigee_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetAnomaly(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_anomaly_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetAnomaly() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_anomaly_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetMotion(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_motion_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetMotion() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_motion_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetClassification(arg2 byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_classification_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.char(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetClassification() (_swig_ret byte) {
	var swig_r byte
	_swig_i_0 := arg1
	swig_r = (byte)(C._wrap_elsetrec_classification_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetDesignation(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_designation_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), *(*C.swig_type_5)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrElsetrec) GetDesignation() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_elsetrec_designation_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrElsetrec) SetEphemeris(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_ephemeris_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetEphemeris() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_elsetrec_ephemeris_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetElnum(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_elnum_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.swig_type_7(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetElnum() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_elsetrec_elnum_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetRevnum(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_revnum_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.swig_type_9(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetRevnum() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_elsetrec_revnum_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetNo_unkozai(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_no_unkozai_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetNo_unkozai() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_no_unkozai_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetAm(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_am_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetAm() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_am_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetEm(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_em_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetEm() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_em_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetIm(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_im_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetIm() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_im_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetOm(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_Om_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetOm() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_Om_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetMm(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_mm_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetMm() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_mm_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetNm(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_nm_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetNm() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_nm_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetTumin(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_tumin_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetTumin() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_tumin_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetMu(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_mu_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetMu() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_mu_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetRadiusearthkm(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_radiusearthkm_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetRadiusearthkm() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_radiusearthkm_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetXke(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_xke_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetXke() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_xke_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetJ2(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_j2_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetJ2() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_j2_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetJ3(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_j3_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetJ3() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_j3_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetJ4(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_j4_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetJ4() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_j4_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetJ3oj2(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_j3oj2_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetJ3oj2() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_j3oj2_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetDia_mm(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_dia_mm_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.swig_type_11(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetDia_mm() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_elsetrec_dia_mm_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetPeriod_sec(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_period_sec_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetPeriod_sec() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_period_sec_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetActive(arg2 byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_active_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.char(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetActive() (_swig_ret byte) {
	var swig_r byte
	_swig_i_0 := arg1
	swig_r = (byte)(C._wrap_elsetrec_active_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetNot_orbital(arg2 byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_not_orbital_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.char(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetNot_orbital() (_swig_ret byte) {
	var swig_r byte
	_swig_i_0 := arg1
	swig_r = (byte)(C._wrap_elsetrec_not_orbital_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrElsetrec) SetRcs_m2(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_elsetrec_rcs_m2_set_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrElsetrec) GetRcs_m2() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_elsetrec_rcs_m2_get_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewElsetrec() (_swig_ret Elsetrec) {
	var swig_r Elsetrec
	swig_r = (Elsetrec)(SwigcptrElsetrec(C._wrap_new_elsetrec_sgp_8b5016feffcb84af()))
	return swig_r
}

func DeleteElsetrec(arg1 Elsetrec) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_elsetrec_sgp_8b5016feffcb84af(C.uintptr_t(_swig_i_0))
}

type Elsetrec interface {
	Swigcptr() uintptr
	SwigIsElsetrec()
	SetNumber(arg2 int64)
	GetNumber() (_swig_ret int64)
	SetYear(arg2 int)
	GetYear() (_swig_ret int)
	SetEpochtynumrev(arg2 int)
	GetEpochtynumrev() (_swig_ret int)
	SetError(arg2 int)
	GetError() (_swig_ret int)
	SetOperationmode(arg2 byte)
	GetOperationmode() (_swig_ret byte)
	SetInit(arg2 byte)
	GetInit() (_swig_ret byte)
	SetMethod(arg2 byte)
	GetMethod() (_swig_ret byte)
	SetIsimp(arg2 int)
	GetIsimp() (_swig_ret int)
	SetAycof(arg2 float64)
	GetAycof() (_swig_ret float64)
	SetCon41(arg2 float64)
	GetCon41() (_swig_ret float64)
	SetCc1(arg2 float64)
	GetCc1() (_swig_ret float64)
	SetCc4(arg2 float64)
	GetCc4() (_swig_ret float64)
	SetCc5(arg2 float64)
	GetCc5() (_swig_ret float64)
	SetD2(arg2 float64)
	GetD2() (_swig_ret float64)
	SetD3(arg2 float64)
	GetD3() (_swig_ret float64)
	SetD4(arg2 float64)
	GetD4() (_swig_ret float64)
	SetDelmo(arg2 float64)
	GetDelmo() (_swig_ret float64)
	SetEta(arg2 float64)
	GetEta() (_swig_ret float64)
	SetArgpdot(arg2 float64)
	GetArgpdot() (_swig_ret float64)
	SetOmgcof(arg2 float64)
	GetOmgcof() (_swig_ret float64)
	SetSinmao(arg2 float64)
	GetSinmao() (_swig_ret float64)
	SetT(arg2 float64)
	GetT() (_swig_ret float64)
	SetT2cof(arg2 float64)
	GetT2cof() (_swig_ret float64)
	SetT3cof(arg2 float64)
	GetT3cof() (_swig_ret float64)
	SetT4cof(arg2 float64)
	GetT4cof() (_swig_ret float64)
	SetT5cof(arg2 float64)
	GetT5cof() (_swig_ret float64)
	SetX1mth2(arg2 float64)
	GetX1mth2() (_swig_ret float64)
	SetX7thm1(arg2 float64)
	GetX7thm1() (_swig_ret float64)
	SetMdot(arg2 float64)
	GetMdot() (_swig_ret float64)
	SetNodedot(arg2 float64)
	GetNodedot() (_swig_ret float64)
	SetXlcof(arg2 float64)
	GetXlcof() (_swig_ret float64)
	SetXmcof(arg2 float64)
	GetXmcof() (_swig_ret float64)
	SetNodecf(arg2 float64)
	GetNodecf() (_swig_ret float64)
	SetIrez(arg2 int)
	GetIrez() (_swig_ret int)
	SetD2201(arg2 float64)
	GetD2201() (_swig_ret float64)
	SetD2211(arg2 float64)
	GetD2211() (_swig_ret float64)
	SetD3210(arg2 float64)
	GetD3210() (_swig_ret float64)
	SetD3222(arg2 float64)
	GetD3222() (_swig_ret float64)
	SetD4410(arg2 float64)
	GetD4410() (_swig_ret float64)
	SetD4422(arg2 float64)
	GetD4422() (_swig_ret float64)
	SetD5220(arg2 float64)
	GetD5220() (_swig_ret float64)
	SetD5232(arg2 float64)
	GetD5232() (_swig_ret float64)
	SetD5421(arg2 float64)
	GetD5421() (_swig_ret float64)
	SetD5433(arg2 float64)
	GetD5433() (_swig_ret float64)
	SetDedt(arg2 float64)
	GetDedt() (_swig_ret float64)
	SetDel1(arg2 float64)
	GetDel1() (_swig_ret float64)
	SetDel2(arg2 float64)
	GetDel2() (_swig_ret float64)
	SetDel3(arg2 float64)
	GetDel3() (_swig_ret float64)
	SetDidt(arg2 float64)
	GetDidt() (_swig_ret float64)
	SetDmdt(arg2 float64)
	GetDmdt() (_swig_ret float64)
	SetDnodt(arg2 float64)
	GetDnodt() (_swig_ret float64)
	SetDomdt(arg2 float64)
	GetDomdt() (_swig_ret float64)
	SetE3(arg2 float64)
	GetE3() (_swig_ret float64)
	SetEe2(arg2 float64)
	GetEe2() (_swig_ret float64)
	SetPeo(arg2 float64)
	GetPeo() (_swig_ret float64)
	SetPgho(arg2 float64)
	GetPgho() (_swig_ret float64)
	SetPho(arg2 float64)
	GetPho() (_swig_ret float64)
	SetPinco(arg2 float64)
	GetPinco() (_swig_ret float64)
	SetPlo(arg2 float64)
	GetPlo() (_swig_ret float64)
	SetSe2(arg2 float64)
	GetSe2() (_swig_ret float64)
	SetSe3(arg2 float64)
	GetSe3() (_swig_ret float64)
	SetSgh2(arg2 float64)
	GetSgh2() (_swig_ret float64)
	SetSgh3(arg2 float64)
	GetSgh3() (_swig_ret float64)
	SetSgh4(arg2 float64)
	GetSgh4() (_swig_ret float64)
	SetSh2(arg2 float64)
	GetSh2() (_swig_ret float64)
	SetSh3(arg2 float64)
	GetSh3() (_swig_ret float64)
	SetSi2(arg2 float64)
	GetSi2() (_swig_ret float64)
	SetSi3(arg2 float64)
	GetSi3() (_swig_ret float64)
	SetSl2(arg2 float64)
	GetSl2() (_swig_ret float64)
	SetSl3(arg2 float64)
	GetSl3() (_swig_ret float64)
	SetSl4(arg2 float64)
	GetSl4() (_swig_ret float64)
	SetGsto(arg2 float64)
	GetGsto() (_swig_ret float64)
	SetXfact(arg2 float64)
	GetXfact() (_swig_ret float64)
	SetXgh2(arg2 float64)
	GetXgh2() (_swig_ret float64)
	SetXgh3(arg2 float64)
	GetXgh3() (_swig_ret float64)
	SetXgh4(arg2 float64)
	GetXgh4() (_swig_ret float64)
	SetXh2(arg2 float64)
	GetXh2() (_swig_ret float64)
	SetXh3(arg2 float64)
	GetXh3() (_swig_ret float64)
	SetXi2(arg2 float64)
	GetXi2() (_swig_ret float64)
	SetXi3(arg2 float64)
	GetXi3() (_swig_ret float64)
	SetXl2(arg2 float64)
	GetXl2() (_swig_ret float64)
	SetXl3(arg2 float64)
	GetXl3() (_swig_ret float64)
	SetXl4(arg2 float64)
	GetXl4() (_swig_ret float64)
	SetXlamo(arg2 float64)
	GetXlamo() (_swig_ret float64)
	SetZmol(arg2 float64)
	GetZmol() (_swig_ret float64)
	SetZmos(arg2 float64)
	GetZmos() (_swig_ret float64)
	SetAtime(arg2 float64)
	GetAtime() (_swig_ret float64)
	SetXli(arg2 float64)
	GetXli() (_swig_ret float64)
	SetXni(arg2 float64)
	GetXni() (_swig_ret float64)
	SetA(arg2 float64)
	GetA() (_swig_ret float64)
	SetAltp(arg2 float64)
	GetAltp() (_swig_ret float64)
	SetAlta(arg2 float64)
	GetAlta() (_swig_ret float64)
	SetDays(arg2 float64)
	GetDays() (_swig_ret float64)
	SetJdsatepoch(arg2 float64)
	GetJdsatepoch() (_swig_ret float64)
	SetJdsatepochF(arg2 float64)
	GetJdsatepochF() (_swig_ret float64)
	SetMean2(arg2 float64)
	GetMean2() (_swig_ret float64)
	SetMean1(arg2 float64)
	GetMean1() (_swig_ret float64)
	SetBstar(arg2 float64)
	GetBstar() (_swig_ret float64)
	SetRcse(arg2 float64)
	GetRcse() (_swig_ret float64)
	SetInclination(arg2 float64)
	GetInclination() (_swig_ret float64)
	SetAscension(arg2 float64)
	GetAscension() (_swig_ret float64)
	SetExcentricity(arg2 float64)
	GetExcentricity() (_swig_ret float64)
	SetPerigee(arg2 float64)
	GetPerigee() (_swig_ret float64)
	SetAnomaly(arg2 float64)
	GetAnomaly() (_swig_ret float64)
	SetMotion(arg2 float64)
	GetMotion() (_swig_ret float64)
	SetClassification(arg2 byte)
	GetClassification() (_swig_ret byte)
	SetDesignation(arg2 string)
	GetDesignation() (_swig_ret string)
	SetEphemeris(arg2 int)
	GetEphemeris() (_swig_ret int)
	SetElnum(arg2 int64)
	GetElnum() (_swig_ret int64)
	SetRevnum(arg2 int64)
	GetRevnum() (_swig_ret int64)
	SetNo_unkozai(arg2 float64)
	GetNo_unkozai() (_swig_ret float64)
	SetAm(arg2 float64)
	GetAm() (_swig_ret float64)
	SetEm(arg2 float64)
	GetEm() (_swig_ret float64)
	SetIm(arg2 float64)
	GetIm() (_swig_ret float64)
	SetOm(arg2 float64)
	GetOm() (_swig_ret float64)
	SetMm(arg2 float64)
	GetMm() (_swig_ret float64)
	SetNm(arg2 float64)
	GetNm() (_swig_ret float64)
	SetTumin(arg2 float64)
	GetTumin() (_swig_ret float64)
	SetMu(arg2 float64)
	GetMu() (_swig_ret float64)
	SetRadiusearthkm(arg2 float64)
	GetRadiusearthkm() (_swig_ret float64)
	SetXke(arg2 float64)
	GetXke() (_swig_ret float64)
	SetJ2(arg2 float64)
	GetJ2() (_swig_ret float64)
	SetJ3(arg2 float64)
	GetJ3() (_swig_ret float64)
	SetJ4(arg2 float64)
	GetJ4() (_swig_ret float64)
	SetJ3oj2(arg2 float64)
	GetJ3oj2() (_swig_ret float64)
	SetDia_mm(arg2 int64)
	GetDia_mm() (_swig_ret int64)
	SetPeriod_sec(arg2 float64)
	GetPeriod_sec() (_swig_ret float64)
	SetActive(arg2 byte)
	GetActive() (_swig_ret byte)
	SetNot_orbital(arg2 byte)
	GetNot_orbital() (_swig_ret byte)
	SetRcs_m2(arg2 float64)
	GetRcs_m2() (_swig_ret float64)
}

func Sgp4init(arg1 Gravconsttype, arg2 byte, arg3 int, arg4 float64, arg5 float64, arg6 float64, arg7 float64, arg8 float64, arg9 float64, arg10 float64, arg11 float64, arg12 float64, arg13 float64, arg14 Elsetrec) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	_swig_i_7 := arg8
	_swig_i_8 := arg9
	_swig_i_9 := arg10
	_swig_i_10 := arg11
	_swig_i_11 := arg12
	_swig_i_12 := arg13
	_swig_i_13 := arg14.Swigcptr()
	swig_r = (bool)(C._wrap_sgp4init_sgp_8b5016feffcb84af(C.swig_intgo(_swig_i_0), C.char(_swig_i_1), C.swig_intgo(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4), C.double(_swig_i_5), C.double(_swig_i_6), C.double(_swig_i_7), C.double(_swig_i_8), C.double(_swig_i_9), C.double(_swig_i_10), C.double(_swig_i_11), C.double(_swig_i_12), C.uintptr_t(_swig_i_13)))
	return swig_r
}

func Getgravconst(arg1 Gravconsttype, arg2 *float64, arg3 *float64, arg4 *float64, arg5 *float64, arg6 *float64, arg7 *float64, arg8 *float64, arg9 *float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	_swig_i_7 := arg8
	_swig_i_8 := arg9
	C._wrap_getgravconst_sgp_8b5016feffcb84af(C.swig_intgo(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_voidp(_swig_i_2), C.swig_voidp(_swig_i_3), C.swig_voidp(_swig_i_4), C.swig_voidp(_swig_i_5), C.swig_voidp(_swig_i_6), C.swig_voidp(_swig_i_7), C.swig_voidp(_swig_i_8))
}

func Gstime(arg1 float64) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_gstime_sgp_8b5016feffcb84af(C.double(_swig_i_0)))
	return swig_r
}

func Sgn(arg1 float64) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_sgn_sgp_8b5016feffcb84af(C.double(_swig_i_0)))
	return swig_r
}

func Mag(arg1 *float64) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_mag_sgp_8b5016feffcb84af(C.swig_voidp(_swig_i_0)))
	return swig_r
}

func Cross(arg1 *float64, arg2 *float64, arg3 *float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_cross_sgp_8b5016feffcb84af(C.swig_voidp(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_voidp(_swig_i_2))
}

func Dot(arg1 *float64, arg2 *float64) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (float64)(C._wrap_dot_sgp_8b5016feffcb84af(C.swig_voidp(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func Angle(arg1 *float64, arg2 *float64) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (float64)(C._wrap_angle_sgp_8b5016feffcb84af(C.swig_voidp(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func Newtonnu(arg1 float64, arg2 float64, arg3 *float64, arg4 *float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_newtonnu_sgp_8b5016feffcb84af(C.double(_swig_i_0), C.double(_swig_i_1), C.swig_voidp(_swig_i_2), C.swig_voidp(_swig_i_3))
}

func Asinh(arg1 float64) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_asinh_sgp_8b5016feffcb84af(C.double(_swig_i_0)))
	return swig_r
}

func Rv2coe(arg1 *float64, arg2 *float64, arg3 float64, arg4 *float64, arg5 *float64, arg6 *float64, arg7 *float64, arg8 *float64, arg9 *float64, arg10 *float64, arg11 *float64, arg12 *float64, arg13 *float64, arg14 *float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	_swig_i_7 := arg8
	_swig_i_8 := arg9
	_swig_i_9 := arg10
	_swig_i_10 := arg11
	_swig_i_11 := arg12
	_swig_i_12 := arg13
	_swig_i_13 := arg14
	C._wrap_rv2coe_sgp_8b5016feffcb84af(C.swig_voidp(_swig_i_0), C.swig_voidp(_swig_i_1), C.double(_swig_i_2), C.swig_voidp(_swig_i_3), C.swig_voidp(_swig_i_4), C.swig_voidp(_swig_i_5), C.swig_voidp(_swig_i_6), C.swig_voidp(_swig_i_7), C.swig_voidp(_swig_i_8), C.swig_voidp(_swig_i_9), C.swig_voidp(_swig_i_10), C.swig_voidp(_swig_i_11), C.swig_voidp(_swig_i_12), C.swig_voidp(_swig_i_13))
}

func Jday(arg1 int, arg2 int, arg3 int, arg4 int, arg5 int, arg6 float64, arg7 *float64, arg8 *float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	_swig_i_7 := arg8
	C._wrap_jday_sgp_8b5016feffcb84af(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3), C.swig_intgo(_swig_i_4), C.double(_swig_i_5), C.swig_voidp(_swig_i_6), C.swig_voidp(_swig_i_7))
}

func Days2mdhms(arg1 int, arg2 float64, arg3 *int, arg4 *int, arg5 *int, arg6 *int, arg7 *float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	C._wrap_days2mdhms_sgp_8b5016feffcb84af(C.swig_intgo(_swig_i_0), C.double(_swig_i_1), C.swig_voidp(_swig_i_2), C.swig_voidp(_swig_i_3), C.swig_voidp(_swig_i_4), C.swig_voidp(_swig_i_5), C.swig_voidp(_swig_i_6))
}

func Invjday(arg1 float64, arg2 float64, arg3 *int, arg4 *int, arg5 *int, arg6 *int, arg7 *int, arg8 *float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	_swig_i_7 := arg8
	C._wrap_invjday_sgp_8b5016feffcb84af(C.double(_swig_i_0), C.double(_swig_i_1), C.swig_voidp(_swig_i_2), C.swig_voidp(_swig_i_3), C.swig_voidp(_swig_i_4), C.swig_voidp(_swig_i_5), C.swig_voidp(_swig_i_6), C.swig_voidp(_swig_i_7))
}


func SGP4(els Elsetrec, since float64) ([]float64, []float64, error) {
  ps := []float64{0.0, 0.0, 0.0}
  vs := []float64{0.0, 0.0, 0.0}

  ModifiedSGP4(els, since, ps, vs)
  switch els.GetError() {
  case 0:
  case 1:
    return nil, nil, fmt.Errorf("mean elements, ecc >= 1.0 or ecc < -0.001 or a < 0.95")
  case 2:
    return nil, nil, fmt.Errorf("mean motion less than 0.0")
  case 3:
    return nil, nil, fmt.Errorf("pert elements, ecc < 0.0  or  ecc > 1.0")
  case 4:
    return nil, nil, fmt.Errorf("semi-latus rectum < 0.0")
  case 5:
    return nil, nil, fmt.Errorf("epoch elements are sub-orbital")
  case 6:
    return nil, nil, fmt.Errorf("satellite has decayed")
  default:
    return nil, nil, fmt.Errorf("unrecognized error")
  }
  return ps, vs, nil
}


