/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: sgp.i

#define SWIGMODULE sgp

#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;




#define swiggo_size_assert_eq(x, y, name) typedef char name[(x-y)*(x-y)*-2+1];
#define swiggo_size_assert(t, n) swiggo_size_assert_eq(sizeof(t), n, swiggo_sizeof_##t##_is_not_##n)

swiggo_size_assert(char, 1)
swiggo_size_assert(short, 2)
swiggo_size_assert(int, 4)
typedef long long swiggo_long_long;
swiggo_size_assert(swiggo_long_long, 8)
swiggo_size_assert(float, 4)
swiggo_size_assert(double, 8)

#ifdef __cplusplus
extern "C" {
#endif
extern void crosscall2(void (*fn)(void *, int), void *, int);
extern char* _cgo_topofstack(void) __attribute__ ((weak));
extern void _cgo_allocate(void *, int);
extern void _cgo_panic(void *, int);
#ifdef __cplusplus
}
#endif

static char *_swig_topofstack() {
  if (_cgo_topofstack) {
    return _cgo_topofstack();
  } else {
    return 0;
  }
}

static void _swig_gopanic(const char *p) {
  struct {
    const char *p;
  } a;
  a.p = p;
  crosscall2(_cgo_panic, &a, (int) sizeof a);
}




#define SWIG_contract_assert(expr, msg) \
  if (!(expr)) { _swig_gopanic(msg); } else


static _gostring_ Swig_AllocateString(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)malloc(l);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}


static void Swig_free(void* p) {
  free(p);
}


  #include "SGP4.h"
  using namespace SGP4Funcs;

#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_sgp_8b5016feffcb84af(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


bool _wrap_modifiedSGP4_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1, _goslice_ _swig_go_2, _goslice_ _swig_go_3) {
  elsetrec *arg1 = 0 ;
  double arg2 ;
  double *arg3 = (double *) 0 ;
  double *arg4 = (double *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  {
    if (_swig_go_2.len == 0) {
      _swig_gopanic("array must contain at least 1 element");
    }
    arg3 = (double *) _swig_go_2.array;
  }
  {
    if (_swig_go_3.len == 0) {
      _swig_gopanic("array must contain at least 1 element");
    }
    arg4 = (double *) _swig_go_3.array;
  }
  
  result = (bool)sgp4(*arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  
  
  
  
  return _swig_go_result;
}


intgo _wrap_wgs72old_sgp_8b5016feffcb84af() {
  int result;
  intgo _swig_go_result;
  
  
  result = wgs72old;
  
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_wgs72_sgp_8b5016feffcb84af() {
  int result;
  intgo _swig_go_result;
  
  
  result = wgs72;
  
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_wgs84_sgp_8b5016feffcb84af() {
  int result;
  intgo _swig_go_result;
  
  
  result = wgs84;
  
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_number_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, long long _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  long arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (long)_swig_go_1; 
  
  if (arg1) (arg1)->satnum = arg2;
  
}


long long _wrap_elsetrec_number_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  long result;
  long long _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (long) ((arg1)->satnum);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_year_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, intgo _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  int arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->epochyr = arg2;
  
}


intgo _wrap_elsetrec_year_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (int) ((arg1)->epochyr);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_epochtynumrev_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, intgo _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  int arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->epochtynumrev = arg2;
  
}


intgo _wrap_elsetrec_epochtynumrev_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (int) ((arg1)->epochtynumrev);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_error_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, intgo _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  int arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->error = arg2;
  
}


intgo _wrap_elsetrec_error_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (int) ((arg1)->error);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_operationmode_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, char _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  char arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (char)_swig_go_1; 
  
  if (arg1) (arg1)->operationmode = arg2;
  
}


char _wrap_elsetrec_operationmode_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  char result;
  char _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (char) ((arg1)->operationmode);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_init_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, char _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  char arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (char)_swig_go_1; 
  
  if (arg1) (arg1)->init = arg2;
  
}


char _wrap_elsetrec_init_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  char result;
  char _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (char) ((arg1)->init);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_method_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, char _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  char arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (char)_swig_go_1; 
  
  if (arg1) (arg1)->method = arg2;
  
}


char _wrap_elsetrec_method_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  char result;
  char _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (char) ((arg1)->method);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_isimp_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, intgo _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  int arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->isimp = arg2;
  
}


intgo _wrap_elsetrec_isimp_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (int) ((arg1)->isimp);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_aycof_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->aycof = arg2;
  
}


double _wrap_elsetrec_aycof_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->aycof);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_con41_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->con41 = arg2;
  
}


double _wrap_elsetrec_con41_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->con41);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_cc1_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->cc1 = arg2;
  
}


double _wrap_elsetrec_cc1_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->cc1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_cc4_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->cc4 = arg2;
  
}


double _wrap_elsetrec_cc4_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->cc4);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_cc5_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->cc5 = arg2;
  
}


double _wrap_elsetrec_cc5_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->cc5);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_d2_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->d2 = arg2;
  
}


double _wrap_elsetrec_d2_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->d2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_d3_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->d3 = arg2;
  
}


double _wrap_elsetrec_d3_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->d3);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_d4_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->d4 = arg2;
  
}


double _wrap_elsetrec_d4_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->d4);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_delmo_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->delmo = arg2;
  
}


double _wrap_elsetrec_delmo_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->delmo);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_eta_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->eta = arg2;
  
}


double _wrap_elsetrec_eta_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->eta);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_argpdot_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->argpdot = arg2;
  
}


double _wrap_elsetrec_argpdot_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->argpdot);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_omgcof_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->omgcof = arg2;
  
}


double _wrap_elsetrec_omgcof_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->omgcof);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_sinmao_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->sinmao = arg2;
  
}


double _wrap_elsetrec_sinmao_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->sinmao);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_t_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->t = arg2;
  
}


double _wrap_elsetrec_t_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->t);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_t2cof_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->t2cof = arg2;
  
}


double _wrap_elsetrec_t2cof_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->t2cof);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_t3cof_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->t3cof = arg2;
  
}


double _wrap_elsetrec_t3cof_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->t3cof);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_t4cof_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->t4cof = arg2;
  
}


double _wrap_elsetrec_t4cof_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->t4cof);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_t5cof_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->t5cof = arg2;
  
}


double _wrap_elsetrec_t5cof_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->t5cof);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_x1mth2_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->x1mth2 = arg2;
  
}


double _wrap_elsetrec_x1mth2_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->x1mth2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_x7thm1_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->x7thm1 = arg2;
  
}


double _wrap_elsetrec_x7thm1_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->x7thm1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_mdot_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->mdot = arg2;
  
}


double _wrap_elsetrec_mdot_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->mdot);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_nodedot_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->nodedot = arg2;
  
}


double _wrap_elsetrec_nodedot_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->nodedot);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_xlcof_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->xlcof = arg2;
  
}


double _wrap_elsetrec_xlcof_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->xlcof);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_xmcof_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->xmcof = arg2;
  
}


double _wrap_elsetrec_xmcof_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->xmcof);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_nodecf_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->nodecf = arg2;
  
}


double _wrap_elsetrec_nodecf_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->nodecf);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_irez_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, intgo _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  int arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->irez = arg2;
  
}


intgo _wrap_elsetrec_irez_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (int) ((arg1)->irez);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_d2201_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->d2201 = arg2;
  
}


double _wrap_elsetrec_d2201_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->d2201);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_d2211_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->d2211 = arg2;
  
}


double _wrap_elsetrec_d2211_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->d2211);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_d3210_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->d3210 = arg2;
  
}


double _wrap_elsetrec_d3210_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->d3210);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_d3222_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->d3222 = arg2;
  
}


double _wrap_elsetrec_d3222_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->d3222);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_d4410_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->d4410 = arg2;
  
}


double _wrap_elsetrec_d4410_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->d4410);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_d4422_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->d4422 = arg2;
  
}


double _wrap_elsetrec_d4422_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->d4422);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_d5220_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->d5220 = arg2;
  
}


double _wrap_elsetrec_d5220_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->d5220);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_d5232_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->d5232 = arg2;
  
}


double _wrap_elsetrec_d5232_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->d5232);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_d5421_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->d5421 = arg2;
  
}


double _wrap_elsetrec_d5421_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->d5421);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_d5433_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->d5433 = arg2;
  
}


double _wrap_elsetrec_d5433_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->d5433);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_dedt_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->dedt = arg2;
  
}


double _wrap_elsetrec_dedt_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->dedt);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_del1_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->del1 = arg2;
  
}


double _wrap_elsetrec_del1_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->del1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_del2_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->del2 = arg2;
  
}


double _wrap_elsetrec_del2_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->del2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_del3_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->del3 = arg2;
  
}


double _wrap_elsetrec_del3_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->del3);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_didt_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->didt = arg2;
  
}


double _wrap_elsetrec_didt_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->didt);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_dmdt_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->dmdt = arg2;
  
}


double _wrap_elsetrec_dmdt_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->dmdt);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_dnodt_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->dnodt = arg2;
  
}


double _wrap_elsetrec_dnodt_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->dnodt);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_domdt_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->domdt = arg2;
  
}


double _wrap_elsetrec_domdt_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->domdt);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_e3_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->e3 = arg2;
  
}


double _wrap_elsetrec_e3_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->e3);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_ee2_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->ee2 = arg2;
  
}


double _wrap_elsetrec_ee2_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->ee2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_peo_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->peo = arg2;
  
}


double _wrap_elsetrec_peo_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->peo);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_pgho_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->pgho = arg2;
  
}


double _wrap_elsetrec_pgho_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->pgho);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_pho_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->pho = arg2;
  
}


double _wrap_elsetrec_pho_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->pho);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_pinco_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->pinco = arg2;
  
}


double _wrap_elsetrec_pinco_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->pinco);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_plo_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->plo = arg2;
  
}


double _wrap_elsetrec_plo_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->plo);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_se2_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->se2 = arg2;
  
}


double _wrap_elsetrec_se2_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->se2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_se3_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->se3 = arg2;
  
}


double _wrap_elsetrec_se3_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->se3);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_sgh2_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->sgh2 = arg2;
  
}


double _wrap_elsetrec_sgh2_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->sgh2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_sgh3_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->sgh3 = arg2;
  
}


double _wrap_elsetrec_sgh3_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->sgh3);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_sgh4_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->sgh4 = arg2;
  
}


double _wrap_elsetrec_sgh4_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->sgh4);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_sh2_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->sh2 = arg2;
  
}


double _wrap_elsetrec_sh2_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->sh2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_sh3_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->sh3 = arg2;
  
}


double _wrap_elsetrec_sh3_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->sh3);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_si2_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->si2 = arg2;
  
}


double _wrap_elsetrec_si2_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->si2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_si3_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->si3 = arg2;
  
}


double _wrap_elsetrec_si3_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->si3);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_sl2_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->sl2 = arg2;
  
}


double _wrap_elsetrec_sl2_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->sl2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_sl3_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->sl3 = arg2;
  
}


double _wrap_elsetrec_sl3_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->sl3);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_sl4_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->sl4 = arg2;
  
}


double _wrap_elsetrec_sl4_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->sl4);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_gsto_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->gsto = arg2;
  
}


double _wrap_elsetrec_gsto_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->gsto);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_xfact_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->xfact = arg2;
  
}


double _wrap_elsetrec_xfact_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->xfact);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_xgh2_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->xgh2 = arg2;
  
}


double _wrap_elsetrec_xgh2_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->xgh2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_xgh3_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->xgh3 = arg2;
  
}


double _wrap_elsetrec_xgh3_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->xgh3);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_xgh4_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->xgh4 = arg2;
  
}


double _wrap_elsetrec_xgh4_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->xgh4);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_xh2_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->xh2 = arg2;
  
}


double _wrap_elsetrec_xh2_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->xh2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_xh3_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->xh3 = arg2;
  
}


double _wrap_elsetrec_xh3_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->xh3);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_xi2_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->xi2 = arg2;
  
}


double _wrap_elsetrec_xi2_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->xi2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_xi3_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->xi3 = arg2;
  
}


double _wrap_elsetrec_xi3_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->xi3);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_xl2_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->xl2 = arg2;
  
}


double _wrap_elsetrec_xl2_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->xl2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_xl3_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->xl3 = arg2;
  
}


double _wrap_elsetrec_xl3_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->xl3);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_xl4_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->xl4 = arg2;
  
}


double _wrap_elsetrec_xl4_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->xl4);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_xlamo_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->xlamo = arg2;
  
}


double _wrap_elsetrec_xlamo_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->xlamo);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_zmol_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->zmol = arg2;
  
}


double _wrap_elsetrec_zmol_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->zmol);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_zmos_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->zmos = arg2;
  
}


double _wrap_elsetrec_zmos_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->zmos);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_atime_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->atime = arg2;
  
}


double _wrap_elsetrec_atime_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->atime);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_xli_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->xli = arg2;
  
}


double _wrap_elsetrec_xli_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->xli);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_xni_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->xni = arg2;
  
}


double _wrap_elsetrec_xni_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->xni);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_a_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->a = arg2;
  
}


double _wrap_elsetrec_a_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->a);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_altp_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->altp = arg2;
  
}


double _wrap_elsetrec_altp_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->altp);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_alta_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->alta = arg2;
  
}


double _wrap_elsetrec_alta_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->alta);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_days_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->epochdays = arg2;
  
}


double _wrap_elsetrec_days_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->epochdays);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_jdsatepoch_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->jdsatepoch = arg2;
  
}


double _wrap_elsetrec_jdsatepoch_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->jdsatepoch);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_jdsatepochF_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->jdsatepochF = arg2;
  
}


double _wrap_elsetrec_jdsatepochF_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->jdsatepochF);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_mean2_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->nddot = arg2;
  
}


double _wrap_elsetrec_mean2_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->nddot);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_mean1_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->ndot = arg2;
  
}


double _wrap_elsetrec_mean1_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->ndot);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_bstar_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->bstar = arg2;
  
}


double _wrap_elsetrec_bstar_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->bstar);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_rcse_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->rcse = arg2;
  
}


double _wrap_elsetrec_rcse_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->rcse);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_inclination_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->inclo = arg2;
  
}


double _wrap_elsetrec_inclination_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->inclo);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_ascension_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->nodeo = arg2;
  
}


double _wrap_elsetrec_ascension_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->nodeo);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_excentricity_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->ecco = arg2;
  
}


double _wrap_elsetrec_excentricity_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->ecco);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_perigee_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->argpo = arg2;
  
}


double _wrap_elsetrec_perigee_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->argpo);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_anomaly_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->mo = arg2;
  
}


double _wrap_elsetrec_anomaly_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->mo);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_motion_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->no_kozai = arg2;
  
}


double _wrap_elsetrec_motion_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->no_kozai);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_classification_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, char _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  char arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (char)_swig_go_1; 
  
  if (arg1) (arg1)->classification = arg2;
  
}


char _wrap_elsetrec_classification_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  char result;
  char _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (char) ((arg1)->classification);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_designation_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, _gostring_ _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  char *arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (char *)_swig_go_1.p; 
  
  {
    if(arg2) {
      strncpy((char*)arg1->intldesg, (const char *)arg2, 11-1);
      arg1->intldesg[11-1] = 0;
    } else {
      arg1->intldesg[0] = 0;
    }
  }
  
}


_gostring_ _wrap_elsetrec_designation_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (char *)(char *) ((arg1)->intldesg);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_elsetrec_ephemeris_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, intgo _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  int arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->ephtype = arg2;
  
}


intgo _wrap_elsetrec_ephemeris_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (int) ((arg1)->ephtype);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_elnum_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, long long _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  long arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (long)_swig_go_1; 
  
  if (arg1) (arg1)->elnum = arg2;
  
}


long long _wrap_elsetrec_elnum_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  long result;
  long long _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (long) ((arg1)->elnum);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_revnum_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, long long _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  long arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (long)_swig_go_1; 
  
  if (arg1) (arg1)->revnum = arg2;
  
}


long long _wrap_elsetrec_revnum_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  long result;
  long long _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (long) ((arg1)->revnum);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_no_unkozai_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->no_unkozai = arg2;
  
}


double _wrap_elsetrec_no_unkozai_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->no_unkozai);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_am_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->am = arg2;
  
}


double _wrap_elsetrec_am_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->am);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_em_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->em = arg2;
  
}


double _wrap_elsetrec_em_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->em);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_im_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->im = arg2;
  
}


double _wrap_elsetrec_im_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->im);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_Om_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->Om = arg2;
  
}


double _wrap_elsetrec_Om_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->Om);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_mm_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->mm = arg2;
  
}


double _wrap_elsetrec_mm_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->mm);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_nm_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->nm = arg2;
  
}


double _wrap_elsetrec_nm_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->nm);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_tumin_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->tumin = arg2;
  
}


double _wrap_elsetrec_tumin_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->tumin);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_mu_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->mu = arg2;
  
}


double _wrap_elsetrec_mu_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->mu);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_radiusearthkm_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->radiusearthkm = arg2;
  
}


double _wrap_elsetrec_radiusearthkm_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->radiusearthkm);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_xke_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->xke = arg2;
  
}


double _wrap_elsetrec_xke_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->xke);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_j2_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->j2 = arg2;
  
}


double _wrap_elsetrec_j2_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->j2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_j3_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->j3 = arg2;
  
}


double _wrap_elsetrec_j3_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->j3);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_j4_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->j4 = arg2;
  
}


double _wrap_elsetrec_j4_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->j4);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_j3oj2_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->j3oj2 = arg2;
  
}


double _wrap_elsetrec_j3oj2_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->j3oj2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_dia_mm_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, long long _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  long arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (long)_swig_go_1; 
  
  if (arg1) (arg1)->dia_mm = arg2;
  
}


long long _wrap_elsetrec_dia_mm_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  long result;
  long long _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (long) ((arg1)->dia_mm);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_period_sec_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->period_sec = arg2;
  
}


double _wrap_elsetrec_period_sec_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->period_sec);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_active_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, char _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  unsigned char arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (unsigned char)_swig_go_1; 
  
  if (arg1) (arg1)->active = arg2;
  
}


char _wrap_elsetrec_active_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  unsigned char result;
  char _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (unsigned char) ((arg1)->active);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_not_orbital_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, char _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  unsigned char arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (unsigned char)_swig_go_1; 
  
  if (arg1) (arg1)->not_orbital = arg2;
  
}


char _wrap_elsetrec_not_orbital_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  unsigned char result;
  char _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (unsigned char) ((arg1)->not_orbital);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_elsetrec_rcs_m2_set_sgp_8b5016feffcb84af(elsetrec *_swig_go_0, double _swig_go_1) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double arg2 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->rcs_m2 = arg2;
  
}


double _wrap_elsetrec_rcs_m2_get_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  result = (double) ((arg1)->rcs_m2);
  _swig_go_result = result; 
  return _swig_go_result;
}


elsetrec *_wrap_new_elsetrec_sgp_8b5016feffcb84af() {
  elsetrec *result = 0 ;
  elsetrec *_swig_go_result;
  
  
  result = (elsetrec *)new elsetrec();
  *(elsetrec **)&_swig_go_result = (elsetrec *)result; 
  return _swig_go_result;
}


void _wrap_delete_elsetrec_sgp_8b5016feffcb84af(elsetrec *_swig_go_0) {
  elsetrec *arg1 = (elsetrec *) 0 ;
  
  arg1 = *(elsetrec **)&_swig_go_0; 
  
  delete arg1;
  
}


bool _wrap_sgp4init_sgp_8b5016feffcb84af(intgo _swig_go_0, char _swig_go_1, intgo _swig_go_2, double _swig_go_3, double _swig_go_4, double _swig_go_5, double _swig_go_6, double _swig_go_7, double _swig_go_8, double _swig_go_9, double _swig_go_10, double _swig_go_11, double _swig_go_12, elsetrec *_swig_go_13) {
  gravconsttype arg1 ;
  char arg2 ;
  int arg3 ;
  double arg4 ;
  double arg5 ;
  double arg6 ;
  double arg7 ;
  double arg8 ;
  double arg9 ;
  double arg10 ;
  double arg11 ;
  double arg12 ;
  double arg13 ;
  elsetrec *arg14 = 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = (gravconsttype)_swig_go_0; 
  arg2 = (char)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  arg4 = (double)_swig_go_3; 
  arg5 = (double)_swig_go_4; 
  arg6 = (double)_swig_go_5; 
  arg7 = (double)_swig_go_6; 
  arg8 = (double)_swig_go_7; 
  arg9 = (double)_swig_go_8; 
  arg10 = (double)_swig_go_9; 
  arg11 = (double)_swig_go_10; 
  arg12 = (double)_swig_go_11; 
  arg13 = (double)_swig_go_12; 
  arg14 = *(elsetrec **)&_swig_go_13; 
  
  result = (bool)SGP4Funcs::sgp4init(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10,arg11,arg12,arg13,*arg14);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_getgravconst_sgp_8b5016feffcb84af(intgo _swig_go_0, double *_swig_go_1, double *_swig_go_2, double *_swig_go_3, double *_swig_go_4, double *_swig_go_5, double *_swig_go_6, double *_swig_go_7, double *_swig_go_8) {
  gravconsttype arg1 ;
  double *arg2 = 0 ;
  double *arg3 = 0 ;
  double *arg4 = 0 ;
  double *arg5 = 0 ;
  double *arg6 = 0 ;
  double *arg7 = 0 ;
  double *arg8 = 0 ;
  double *arg9 = 0 ;
  
  arg1 = (gravconsttype)_swig_go_0; 
  arg2 = *(double **)&_swig_go_1; 
  arg3 = *(double **)&_swig_go_2; 
  arg4 = *(double **)&_swig_go_3; 
  arg5 = *(double **)&_swig_go_4; 
  arg6 = *(double **)&_swig_go_5; 
  arg7 = *(double **)&_swig_go_6; 
  arg8 = *(double **)&_swig_go_7; 
  arg9 = *(double **)&_swig_go_8; 
  
  SGP4Funcs::getgravconst(arg1,*arg2,*arg3,*arg4,*arg5,*arg6,*arg7,*arg8,*arg9);
  
}


double _wrap_gstime_sgp_8b5016feffcb84af(double _swig_go_0) {
  double arg1 ;
  double result;
  double _swig_go_result;
  
  arg1 = (double)_swig_go_0; 
  
  result = (double)SGP4Funcs::gstime(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


double _wrap_sgn_sgp_8b5016feffcb84af(double _swig_go_0) {
  double arg1 ;
  double result;
  double _swig_go_result;
  
  arg1 = (double)_swig_go_0; 
  
  result = (double)SGP4Funcs::sgn(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


double _wrap_mag_sgp_8b5016feffcb84af(double *_swig_go_0) {
  double *arg1 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(double **)&_swig_go_0; 
  
  result = (double)SGP4Funcs::mag(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_cross_sgp_8b5016feffcb84af(double *_swig_go_0, double *_swig_go_1, double *_swig_go_2) {
  double *arg1 ;
  double *arg2 ;
  double *arg3 ;
  
  arg1 = *(double **)&_swig_go_0; 
  arg2 = *(double **)&_swig_go_1; 
  arg3 = *(double **)&_swig_go_2; 
  
  SGP4Funcs::cross(arg1,arg2,arg3);
  
}


double _wrap_dot_sgp_8b5016feffcb84af(double *_swig_go_0, double *_swig_go_1) {
  double *arg1 ;
  double *arg2 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(double **)&_swig_go_0; 
  arg2 = *(double **)&_swig_go_1; 
  
  result = (double)SGP4Funcs::dot(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


double _wrap_angle_sgp_8b5016feffcb84af(double *_swig_go_0, double *_swig_go_1) {
  double *arg1 ;
  double *arg2 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(double **)&_swig_go_0; 
  arg2 = *(double **)&_swig_go_1; 
  
  result = (double)SGP4Funcs::angle(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_newtonnu_sgp_8b5016feffcb84af(double _swig_go_0, double _swig_go_1, double *_swig_go_2, double *_swig_go_3) {
  double arg1 ;
  double arg2 ;
  double *arg3 = 0 ;
  double *arg4 = 0 ;
  
  arg1 = (double)_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  arg3 = *(double **)&_swig_go_2; 
  arg4 = *(double **)&_swig_go_3; 
  
  SGP4Funcs::newtonnu(arg1,arg2,*arg3,*arg4);
  
}


double _wrap_asinh_sgp_8b5016feffcb84af(double _swig_go_0) {
  double arg1 ;
  double result;
  double _swig_go_result;
  
  arg1 = (double)_swig_go_0; 
  
  result = (double)SGP4Funcs::asinh(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_rv2coe_sgp_8b5016feffcb84af(double *_swig_go_0, double *_swig_go_1, double _swig_go_2, double *_swig_go_3, double *_swig_go_4, double *_swig_go_5, double *_swig_go_6, double *_swig_go_7, double *_swig_go_8, double *_swig_go_9, double *_swig_go_10, double *_swig_go_11, double *_swig_go_12, double *_swig_go_13) {
  double *arg1 ;
  double *arg2 ;
  double arg3 ;
  double *arg4 = 0 ;
  double *arg5 = 0 ;
  double *arg6 = 0 ;
  double *arg7 = 0 ;
  double *arg8 = 0 ;
  double *arg9 = 0 ;
  double *arg10 = 0 ;
  double *arg11 = 0 ;
  double *arg12 = 0 ;
  double *arg13 = 0 ;
  double *arg14 = 0 ;
  
  arg1 = *(double **)&_swig_go_0; 
  arg2 = *(double **)&_swig_go_1; 
  arg3 = (double)_swig_go_2; 
  arg4 = *(double **)&_swig_go_3; 
  arg5 = *(double **)&_swig_go_4; 
  arg6 = *(double **)&_swig_go_5; 
  arg7 = *(double **)&_swig_go_6; 
  arg8 = *(double **)&_swig_go_7; 
  arg9 = *(double **)&_swig_go_8; 
  arg10 = *(double **)&_swig_go_9; 
  arg11 = *(double **)&_swig_go_10; 
  arg12 = *(double **)&_swig_go_11; 
  arg13 = *(double **)&_swig_go_12; 
  arg14 = *(double **)&_swig_go_13; 
  
  SGP4Funcs::rv2coe(arg1,arg2,arg3,*arg4,*arg5,*arg6,*arg7,*arg8,*arg9,*arg10,*arg11,*arg12,*arg13,*arg14);
  
}


void _wrap_jday_sgp_8b5016feffcb84af(intgo _swig_go_0, intgo _swig_go_1, intgo _swig_go_2, intgo _swig_go_3, intgo _swig_go_4, double _swig_go_5, double *_swig_go_6, double *_swig_go_7) {
  int arg1 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  int arg5 ;
  double arg6 ;
  double *arg7 = 0 ;
  double *arg8 = 0 ;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = (int)_swig_go_4; 
  arg6 = (double)_swig_go_5; 
  arg7 = *(double **)&_swig_go_6; 
  arg8 = *(double **)&_swig_go_7; 
  
  SGP4Funcs::jday(arg1,arg2,arg3,arg4,arg5,arg6,*arg7,*arg8);
  
}


void _wrap_days2mdhms_sgp_8b5016feffcb84af(intgo _swig_go_0, double _swig_go_1, int *_swig_go_2, int *_swig_go_3, int *_swig_go_4, int *_swig_go_5, double *_swig_go_6) {
  int arg1 ;
  double arg2 ;
  int *arg3 = 0 ;
  int *arg4 = 0 ;
  int *arg5 = 0 ;
  int *arg6 = 0 ;
  double *arg7 = 0 ;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  arg3 = *(int **)&_swig_go_2; 
  arg4 = *(int **)&_swig_go_3; 
  arg5 = *(int **)&_swig_go_4; 
  arg6 = *(int **)&_swig_go_5; 
  arg7 = *(double **)&_swig_go_6; 
  
  SGP4Funcs::days2mdhms(arg1,arg2,*arg3,*arg4,*arg5,*arg6,*arg7);
  
}


void _wrap_invjday_sgp_8b5016feffcb84af(double _swig_go_0, double _swig_go_1, int *_swig_go_2, int *_swig_go_3, int *_swig_go_4, int *_swig_go_5, int *_swig_go_6, double *_swig_go_7) {
  double arg1 ;
  double arg2 ;
  int *arg3 = 0 ;
  int *arg4 = 0 ;
  int *arg5 = 0 ;
  int *arg6 = 0 ;
  int *arg7 = 0 ;
  double *arg8 = 0 ;
  
  arg1 = (double)_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  arg3 = *(int **)&_swig_go_2; 
  arg4 = *(int **)&_swig_go_3; 
  arg5 = *(int **)&_swig_go_4; 
  arg6 = *(int **)&_swig_go_5; 
  arg7 = *(int **)&_swig_go_6; 
  arg8 = *(double **)&_swig_go_7; 
  
  SGP4Funcs::invjday(arg1,arg2,*arg3,*arg4,*arg5,*arg6,*arg7,*arg8);
  
}


#ifdef __cplusplus
}
#endif

